apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-api
  template:
    metadata:
      labels:
        app: master-api
    spec:
      containers:
        - name: master-api
          image:  master-api
          imagePullPolicy: IfNotPresent
          # use secret file instead
          env:
            - name: RMQ_URL
              value: 'amqp://user:password@rabbitmq-srv:5672'
---
apiVersion: v1
kind: Service
metadata:
  name: master-api-srv
spec:
  selector:
    app: master-api
  ports:
   - name: http
     protocol: TCP
     port: 3000
     targetPort: 3000

# node port service
---
apiVersion: v1
kind: Service
metadata:
  name: master-api-nodeport-srv
spec:
  type: NodePort
  selector:
    app: master-api # we are telling this nodePort service here to find all the pods that have a lable of posts
  ports:
   - name: http
     protocol: TCP
     port: 3003
     targetPort: 3000
