apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-nodes-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave-nodes
  template:
    metadata:
      labels:
        app: slave-nodes
    spec:
      containers:
        - name: slave-api
          image: slave-api
          imagePullPolicy: IfNotPresent
          env:
            - name: RMQ_URL
            # use secret file instead
              value: 'amqp://user:password@rabbitmq-srv:5672'

# dont need any service here bcz they will be communicatin asynchoronously
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: slave-nodes-srv
# spec:
#   selector:
#     app: 
#   ports:
#    - name: http
#      protocol: TCP
#      port: 3000

# ---
# # node port service
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-nodeport-srv
# spec:
#   type: NodePort
#   selector:
#     app: rabbitmq # we are telling this nodePort service here to find all the pods that have a lable of posts
#   ports:
#    - name: http
#      protocol: TCP
#      port: 15672
#    - name: prometheus
#      protocol: TCP
#      port: 15692
#    - name: amqp
#      protocol: TCP
#      port: 5672
